name : Actions workflow

on : 
  #schedule:
   # - cron : "0/5 * * * *"
   # - cron:  "0/6 * * * *"
  repository_dispatch:
    types: [build]
  pull_request:
    types: [closed, assigned, opened, reopened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: payload
        run : echo ${{github.event.client_payload.env}}

      - name: List files
        run : |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"

      - name: checkout
        uses: actions/checkout@v3.0.0

      - name: list files after checkout
        run : |
          pwd
          ls


      - name: Simple js action
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: john
      - name: log greeting time
        run: echo "${{ steps.greet.outputs.time }}"
       
